
// DEFAULT ACTIONS TYPE
export const GET_USER = "GET_USER";
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";

// GUIDE ACTIONS TYPE
export const GET_GUIDES = "GET_GUIDES";

// FORM ACTIONS TYPE
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const HANDLE_SUBMIT = "HANDLE_SUBMIT";